import type { BrandConfig } from './types';

/**
 * Nethen — Rental Motor Semarang
 * Motorcycle rental brand for Semarang area
 */
export const nethenBrand: BrandConfig = {
  id: 'nethen',
  shortName: 'Nethen',
  legalName: 'Nethen Rental Motor Semarang',
  city: 'Semarang',
  tagline: 'Kebebasan Menjelajah Dimulai di Sini.',
  description:
    'Sewa motor di Semarang dengan mudah dan cepat. Harga terjangkau, unit terawat, layanan terpercaya, siap pakai. Pesan sekarang!',
  siteUrl: 'https://nethenrental.com',
  whatsappNumber: '6282329616166',
  gtmId: 'GTM-KM5GLHDW',
  adsId: 'AW-11380968042',
  logoPath: '/images/Nethen_Rental_Motor_logo_design_20260926163534.jpg',
  ogImagePath: '/images/Scooter_parked_for_rental_2K_20260926163425.jpg',
  social: {
    instagram: 'https://www.instagram.com/inforentalmotorbandung/',
    tiktok: 'https://www.tiktok.com/@nethen.rental',
  },
  navLinks: [
    { href: '/armada', label: 'Armada' },
    { href: '/harga', label: 'Harga' },
    { href: '/galeri', label: 'Galeri' },
    { href: '/tentang-kami', label: 'Tentang Kami' },
    { href: '/lokasi', label: 'Lokasi' },
    { href: '/faq', label: 'FAQ' },
    { href: '/snk', label: 'S&K' },
  ],
  seoLocations: [
    { name: 'Sewa Motor Simpang Lima', href: '/sewa-motor-simpang-lima' },
    { name: 'Rental Motor Lawang Sewu', href: '/sewa-motor-lawang-sewu' },
    { name: 'Sewa Motor Kota Lama', href: '/sewa-motor-kota-lama' },
    { name: 'Rental Motor Tugu Muda', href: '/sewa-motor-tugu-muda' },
    { name: 'Sewa Motor Diponegoro', href: '/sewa-motor-diponegoro' },
    { name: 'Rental Motor Pandanaran', href: '/sewa-motor-pandanaran' },
    { name: 'Sewa Motor Stasiun Tawang', href: '/sewa-motor-stasiun-tawang' },
    { name: 'Rental Motor Bandara Ahmad Yani', href: '/sewa-motor-bandara-ahmad-yani' },
    { name: 'Sewa Motor Banyumanik', href: '/sewa-motor-banyumanik' },
  ],
  homepageSections: [
    'Header',
    'Hero',
    'Keunggulan',
    'Armada',
    'Proses',
    'FAQ',
    'OrderForm (#pesan)',
    'CTA',
    'Footer',
    'FloatingWhatsApp',
    'PromoPopup',
  ],
  promoPopup: {
    enabled: true,
    delayMs: 12000,
    eyebrow: 'Unit motor terbatas hari ini',
    title: 'Pesan sekarang, keburu kehabisan!',
    description:
      'Weekend & musim liburan unit cepat ludes. Amankan motor favorit Anda sekarang sebelum penuh.',
    primaryCta: 'Pesan Sekarang',
    secondaryCta: 'Chat WhatsApp',
    footnote: 'Respon cepat via WhatsApp · Harga tanya admin',
  },
  business: {
    streetAddress: 'Jl. Pandanaran No. 123, Mugassari, Kec. Semarang Selatan',
    addressLocality: 'Semarang',
    addressRegion: 'Jawa Tengah',
    postalCode: '50241',
    addressCountry: 'ID',
    latitude: -6.9667,
    longitude: 110.4167,
    openingHours: 'Mo-Su 05:00-21:30',
    priceRange: 'Harga mulai Rp 60.000/hari',
  },
  theme: {
    background: '0 0% 100%',
    foreground: '222.2 84% 4.9%',
    primary: '142.1 76.2% 36.3%',
    primaryForeground: '355.7 100% 97.3%',
    muted: '210 40% 96.1%',
    mutedForeground: '215.4 16.3% 46.9%',
    border: '214.3 31.8% 91.4%',
    ring: '142.1 76.2% 36.3%',
    radius: '0.625rem',
    fontSans: 'Inter',
    fontDisplay: 'Plus Jakarta Sans',
  },
};